services:
  data-fetching-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/data-fetching-service:latest
    container_name: data-fetching-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: ghcr.io/aet-devops25/team-rest-in-peace/database:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env

  genai-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/genai-service:latest
    container_name: genai-service
    ports:
      - "8000:8000"
    env_file:
      - .env

  browsing-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/browsing-service:latest
    container_name: browsing-service
    ports:
      - "8081:8081"
    env_file:
      - .env

  notification-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/notification-service:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    env_file:
      - .env