services:
  data-fetching-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/data-fetching-service:latest
    container_name: data-fetching-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: ghcr.io/aet-devops25/team-rest-in-peace/database:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env

  genai-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/genai-service:latest
    container_name: genai-service
    ports:
      - "8000:8000"
    env_file:
      - .env

  browsing-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/browsing-service:latest
    container_name: browsing-service
    ports:
      - "8081:8081"
    env_file:
      - .env

  notification-service:
    image: ghcr.io/aet-devops25/team-rest-in-peace/notification-service:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - genai-service
      - data-fetching-service
      - browsing-service
      - notification-service

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - genai-service
      - data-fetching-service
      - browsing-service
      - notification-service

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      volumes:
        - grafana-storage:/var/lib/grafana

  volumes:
    grafana-storage: