services:
  db:
    build: database
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: welovedevops

  api:
    build: genai
    container_name: genai
    ports:
      - "8000:8000"
    env_file:
      - .env