global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'genai-service'
    static_configs:
      - targets: ['genai-service:8000']

  - job_name: 'data-fetching-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['data-fetching-service:8080']

  - job_name: 'browsing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['browsing-service:8081']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8082']