apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: browsing-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: browsing-service
      monitoring: "true"
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
