apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: genai-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: genai-service
      monitoring: "true"
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
