---
apiVersion: v1
kind: Secret
metadata:
  name: data-fetching-service-secret
type: Opaque
data:
  DF_DB_PASSWORD: {{ .Values.dataFetchingService.db.password | b64enc | quote }}
  DF_BUNDESTAG_API_KEY: {{ .Values.dataFetchingService.bundestagApiKey | b64enc | quote }}