---
apiVersion: v1
kind: Secret
metadata:
  name: genai-service-secret
type: Opaque
data:
  NLP_DB_PASSWORD: {{ .Values.genaiService.db.password | b64enc | quote }}
  NLP_GENAI_API_KEY: {{ .Values.genaiService.apiKey | b64enc | quote }}