---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
data:
  NS_DB_PASSWORD: {{ .Values.notificationService.db.password | b64enc | quote }}
  NS_MAIL_PASSWORD: {{ .Values.notificationService.mail.password | b64enc | quote }}