---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  BS_DB_PASSWORD: {{ .Values.browsingService.db.password | b64enc | quote }}
  NS_DB_PASSWORD: {{ .Values.notificationService.db.password | b64enc | quote }}
  NLP_DB_PASSWORD: {{ .Values.genaiService.db.password | b64enc | quote }}
  DF_DB_PASSWORD: {{ .Values.dataFetchingService.db.password | b64enc | quote }}