---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.notificationService.image }}:{{ .Values.notificationService.tag }}
          imagePullPolicy: {{ .Values.notificationService.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.notificationService.port }}
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
