# Default values for policy-watch Helm chart

url: "rest-in-peace.student.k8s.aet.cit.tum.de"

db:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/database"
  tag: "latest"
  imagePullPolicy: Always
  port: 5432
  name: "policy_watch_db"
  host: "postgres-service"
  user: "postgres"
  password: "your_postgres_password"
  persistentVolume:
    size: "5Gi"

genaiService:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/genai-service"
  tag: "latest"
  imagePullPolicy: Always
  port: 8000
  apiKey: "your_genai_api_key"
  db:
    username: "genai_user"
    password: "genai_password"

dataFetchingService:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/data-fetching-service"
  tag: "latest"
  imagePullPolicy: Always
  port: 8080
  bundestagApiKey: "your_bundestag_api_key"
  db:
    username: "data_fetching_user"
    password: "data_fetching_password"

browsingService:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/browsing-service"
  tag: "latest"
  imagePullPolicy: Always
  port: 8081
  db:
    username: "browsing_user"
    password: "browsing_password"

notificationService:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/notification-service"
  tag: "latest"
  imagePullPolicy: Always
  port: 8082
  mailProviderApiKey: "your_mail_provider_api_key"
  db:
    username: "notification_user"
    password: "notification_password"

client:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/client"
  tag: "latest"
  imagePullPolicy: Always
  port: 3000

prometheus:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/prometheus:latest"
  port: 9090

grafana:
  image: "ghcr.io/aet-devops25/team-rest-in-peace/grafana:latest"
  port: 9091
