---
apiVersion: v1
kind: Service
metadata:
  name: browsing-service
  labels:
    app: browsing-service
    monitoring: "true"
spec:
  selector:
    app: browsing-service
  ports:
    - name: http
      port: {{ .Values.browsingService.port }}
