---
apiVersion: v1
kind: Service
metadata:
  name: data-fetching-service
  labels:
    app: data-fetching-service
    monitoring: "true"
spec:
  selector:
    app: data-fetching-service
  ports:
    - name: http
      port: {{ .Values.dataFetchingService.port }}
