apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: team-rest-in-peace-monitoring
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: 9091
      targetPort: 3000
