---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    monitoring: "true"
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: {{ .Values.notificationService.port }}
