apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: team-rest-in-peace-monitoring
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
