---
apiVersion: v1
kind: ConfigMap
metadata:
  name: browsing-service-config
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  BS_DB_USERNAME: {{ .Values.browsingService.db.username | quote }}