---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  VITE_BROWSING_BASE_URL:  {{ printf "https://%s/api/browse" .Values.url | quote }}
  VITE_NOTIFICATIONS_BASE_URL: {{ printf "https://%s/api/notification" .Values.url | quote }}