---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-fetching-service-config
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DF_DB_USERNAME: {{ .Values.dataFetchingService.db.username | quote }}
  GS_BASEURL: {{ printf "https://%s/api/genai" .Values.url | quote }}
  NS_BASEURL: {{ printf "https://%s/api/notify" .Values.url | quote }}