---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genai-service-config
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  NLP_DB_USERNAME: {{ .Values.genaiService.db.username | quote }}