# Ingress for Client (no rewrite)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-watch-client-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.url | quote }}
      secretName: policy-watch-tls
  rules:
    - host: {{ .Values.url | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.port }}

---

# Ingress for API services (with rewrite)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-watch-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.url | quote }}
      secretName: policy-watch-tls
  rules:
    - host: {{ .Values.url | quote }}
      http:
        paths:
          - path: /api/genai(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: genai-service
                port:
                  number: {{ .Values.genaiService.port }}
          - path: /api/data(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-fetching-service
                port:
                  number: {{ .Values.dataFetchingService.port }}
          - path: /api/browse(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: browsing-service
                port:
                  number: {{ .Values.browsingService.port }}
          - path: /api/notification(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-service
                port:
                  number: {{ .Values.notificationService.port }}