apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-watch-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - {{ .Values.url | quote }}
      secretName: policy-watch-tls
  rules:
    - host: {{ .Values.url | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.port }}
          - path: /api/genai
            pathType: Prefix
            backend:
              service:
                name: genai-service
                port:
                  number: {{ .Values.genaiService.port }}
          - path: /api/data
            pathType: Prefix
            backend:
              service:
                name: data-fetching-service
                port:
                  number: {{ .Values.dataFetchingService.port }}
          - path: /api/browse
            pathType: Prefix
            backend:
              service:
                name: browsing-service
                port:
                  number: {{ .Values.browsingService.port }}
          - path: /api/notify
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: {{ .Values.notificationService.port }}
