name: CI for Data Fetching Service

on:
  push:
    branches:
      - main
    paths:
      - 'browsing-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'browsing-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./browsing-service/gradlew

      - name: Lin and test Project
        run: ./gradlew check
        working-directory: ./browsing-service
