name: Deploy to Kubernetes with helm

on:
  workflow_run:
    workflows: [Build Docker Images]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Set short commit hash
        id: vars
        run: echo "SHORT_SHA=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Deploy the Helm chart
        run: |
          helm upgrade policy-watch helm/policy-watch \
            --install \
            --create-namespace \
            --namespace team-rest-in-peace \
            --set-string db.name="${{ vars.POSTGRES_DB }}" \
            --set-string db.user="${{ vars.POSTGRES_USER }}" \
            --set-string db.password="${{ secrets.POSTGRES_PASSWORD }}" \
            --set-string genaiService.apiKey="${{ secrets.NLP_GENAI_API_KEY }}" \
            --set-string genaiService.db.username="${{ vars.NLP_DB_USERNAME }}" \
            --set-string genaiService.db.password="${{ secrets.NLP_DB_PASSWORD }}" \
            --set-string dataFetchingService.bundestagApiKey="${{ secrets.DF_BUNDESTAG_API_KEY }}" \
            --set-string dataFetchingService.db.username="${{ vars.DF_DB_USERNAME }}" \
            --set-string dataFetchingService.db.password="${{ vars.DF_DB_PASSWORD }}" \
            --set-string browsingService.db.username="${{ vars.BS_DB_USERNAME }}" \
            --set-string browsingService.db.password="${{ secrets.BS_DB_PASSWORD }}" \
            --set-string notificationService.mail.password="${{ secrets.NS_MAIL_PASSWORD }}" \
            --set-string notificationService.db.username="${{ vars.NS_DB_USERNAME }}" \
            --set-string notificationService.db.password="${{ secrets.NS_DB_PASSWORD }}" \
            --set-string genaiService.tag="$SHORT_SHA" \
            --set-string dataFetchingService.tag="$SHORT_SHA" \
            --set-string browsingService.tag="$SHORT_SHA" \
            --set-string notificationService.tag="$SHORT_SHA" \
            --set-string client.tag="$SHORT_SHA"
